.PHONY: clean All

All:
	@echo "----------Building project:[ DinnerBillCalculator - Debug ]----------"
	@cd "DinnerBillCalculator" && "$(MAKE)" -f  "DinnerBillCalculator.mk"
clean:
	@echo "----------Cleaning project:[ DinnerBillCalculator - Debug ]----------"
	@cd "DinnerBillCalculator" && "$(MAKE)" -f  "DinnerBillCalculator.mk" clean
